apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: movieapi:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: POSTGRES_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_PASSWORD
          - name: DB_HOST
            value: db-service
          - name: DB_PORT
            value: '5432'
          - name: DB_DBNAME
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: POSTGRES_DB
        ports:
        - containerPort: 8080
