apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:17
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: movie
          - name: POSTGRES_PASSWORD
            value: moviepassword
          - name: POSTGRES_DB
            value: dbmovies
        volumeMounts:
          - mountPath: /var/lib/postgresql/data/
            name: movie-storage
      volumes:
        - name: movie-storage
          persistentVolumeClaim:
            claimName: db-pvc
